/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExamAnswer { 'questionId' : bigint, 'selectedIndex' : bigint }
export interface ExamAttempt {
  'id' : bigint,
  'completedAt' : bigint,
  'startedAt' : bigint,
  'userId' : Principal,
  'answers' : Array<UserAnswer>,
  'topicBreakdown' : Array<[bigint, bigint, bigint]>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'examId' : bigint,
}
export interface MockExam {
  'id' : bigint,
  'title' : string,
  'questionIds' : Array<bigint>,
}
export interface PracticeAttempt {
  'id' : bigint,
  'userId' : Principal,
  'isCorrect' : boolean,
  'timestamp' : bigint,
  'questionId' : bigint,
  'selectedIndex' : bigint,
  'topicId' : bigint,
}
export interface PracticeResult {
  'attempt' : PracticeAttempt,
  'correctIndex' : bigint,
  'explanation' : string,
  'isCorrect' : boolean,
}
export interface Question {
  'id' : bigint,
  'correctIndex' : bigint,
  'difficulty' : string,
  'explanation' : string,
  'stem' : string,
  'options' : Array<string>,
  'topicId' : bigint,
}
export interface Topic {
  'id' : bigint,
  'weightMax' : bigint,
  'weightMin' : bigint,
  'title' : string,
  'description' : string,
  'learningObjectives' : Array<string>,
}
export interface UserAnswer {
  'isCorrect' : boolean,
  'timestamp' : bigint,
  'questionId' : bigint,
  'selectedIndex' : bigint,
}
export interface UserStats {
  'totalPracticeAttempts' : bigint,
  'userId' : Principal,
  'totalPracticeCorrect' : bigint,
  'topicStats' : Array<[bigint, bigint, bigint]>,
  'lastActiveDate' : string,
  'studyStreak' : bigint,
}
export interface _SERVICE {
  'getMockExam' : ActorMethod<[bigint], [] | [MockExam]>,
  'getMockExamQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getMockExams' : ActorMethod<[], Array<MockExam>>,
  'getMyExamHistory' : ActorMethod<[], Array<ExamAttempt>>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getMyTopicStats' : ActorMethod<[], Array<[bigint, bigint, bigint]>>,
  'getQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getTopic' : ActorMethod<[bigint], [] | [Topic]>,
  'getTopics' : ActorMethod<[], Array<Topic>>,
  'submitExamAttempt' : ActorMethod<[bigint, Array<ExamAnswer>], ExamAttempt>,
  'submitPracticeAnswer' : ActorMethod<
    [bigint, bigint, bigint],
    PracticeResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];