/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MockExam = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'questionIds' : IDL.Vec(IDL.Nat),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctIndex' : IDL.Nat,
  'difficulty' : IDL.Text,
  'explanation' : IDL.Text,
  'stem' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'topicId' : IDL.Nat,
});
export const UserAnswer = IDL.Record({
  'isCorrect' : IDL.Bool,
  'timestamp' : IDL.Int,
  'questionId' : IDL.Nat,
  'selectedIndex' : IDL.Nat,
});
export const ExamAttempt = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'startedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(UserAnswer),
  'topicBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat)),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'examId' : IDL.Nat,
});
export const UserStats = IDL.Record({
  'totalPracticeAttempts' : IDL.Nat,
  'userId' : IDL.Principal,
  'totalPracticeCorrect' : IDL.Nat,
  'topicStats' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat)),
  'lastActiveDate' : IDL.Text,
  'studyStreak' : IDL.Nat,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'weightMax' : IDL.Nat,
  'weightMin' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'learningObjectives' : IDL.Vec(IDL.Text),
});
export const ExamAnswer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedIndex' : IDL.Nat,
});
export const PracticeAttempt = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'isCorrect' : IDL.Bool,
  'timestamp' : IDL.Int,
  'questionId' : IDL.Nat,
  'selectedIndex' : IDL.Nat,
  'topicId' : IDL.Nat,
});
export const PracticeResult = IDL.Record({
  'attempt' : PracticeAttempt,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'isCorrect' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getMockExam' : IDL.Func([IDL.Nat], [IDL.Opt(MockExam)], ['query']),
  'getMockExamQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getMockExams' : IDL.Func([], [IDL.Vec(MockExam)], ['query']),
  'getMyExamHistory' : IDL.Func([], [IDL.Vec(ExamAttempt)], ['query']),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getMyTopicStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getTopic' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
  'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'submitExamAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(ExamAnswer)],
      [ExamAttempt],
      [],
    ),
  'submitPracticeAnswer' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [PracticeResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MockExam = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'questionIds' : IDL.Vec(IDL.Nat),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctIndex' : IDL.Nat,
    'difficulty' : IDL.Text,
    'explanation' : IDL.Text,
    'stem' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'topicId' : IDL.Nat,
  });
  const UserAnswer = IDL.Record({
    'isCorrect' : IDL.Bool,
    'timestamp' : IDL.Int,
    'questionId' : IDL.Nat,
    'selectedIndex' : IDL.Nat,
  });
  const ExamAttempt = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'startedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(UserAnswer),
    'topicBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat)),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'examId' : IDL.Nat,
  });
  const UserStats = IDL.Record({
    'totalPracticeAttempts' : IDL.Nat,
    'userId' : IDL.Principal,
    'totalPracticeCorrect' : IDL.Nat,
    'topicStats' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat)),
    'lastActiveDate' : IDL.Text,
    'studyStreak' : IDL.Nat,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'weightMax' : IDL.Nat,
    'weightMin' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'learningObjectives' : IDL.Vec(IDL.Text),
  });
  const ExamAnswer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedIndex' : IDL.Nat,
  });
  const PracticeAttempt = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'isCorrect' : IDL.Bool,
    'timestamp' : IDL.Int,
    'questionId' : IDL.Nat,
    'selectedIndex' : IDL.Nat,
    'topicId' : IDL.Nat,
  });
  const PracticeResult = IDL.Record({
    'attempt' : PracticeAttempt,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'isCorrect' : IDL.Bool,
  });
  
  return IDL.Service({
    'getMockExam' : IDL.Func([IDL.Nat], [IDL.Opt(MockExam)], ['query']),
    'getMockExamQuestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getMockExams' : IDL.Func([], [IDL.Vec(MockExam)], ['query']),
    'getMyExamHistory' : IDL.Func([], [IDL.Vec(ExamAttempt)], ['query']),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getMyTopicStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getTopic' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
    'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'submitExamAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(ExamAnswer)],
        [ExamAttempt],
        [],
      ),
    'submitPracticeAnswer' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [PracticeResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };