/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PracticeResult {
    attempt: PracticeAttempt;
    correctIndex: bigint;
    explanation: string;
    isCorrect: boolean;
}
export interface ExamAttempt {
    id: bigint;
    completedAt: bigint;
    startedAt: bigint;
    userId: Principal;
    answers: Array<UserAnswer>;
    topicBreakdown: Array<[bigint, bigint, bigint]>;
    score: bigint;
    totalQuestions: bigint;
    examId: bigint;
}
export interface ExamAnswer {
    questionId: bigint;
    selectedIndex: bigint;
}
export interface UserAnswer {
    isCorrect: boolean;
    timestamp: bigint;
    questionId: bigint;
    selectedIndex: bigint;
}
export interface PracticeAttempt {
    id: bigint;
    userId: Principal;
    isCorrect: boolean;
    timestamp: bigint;
    questionId: bigint;
    selectedIndex: bigint;
    topicId: bigint;
}
export interface Topic {
    id: bigint;
    weightMax: bigint;
    weightMin: bigint;
    title: string;
    description: string;
    learningObjectives: Array<string>;
}
export interface Question {
    id: bigint;
    correctIndex: bigint;
    difficulty: string;
    explanation: string;
    stem: string;
    options: Array<string>;
    topicId: bigint;
}
export interface MockExam {
    id: bigint;
    title: string;
    questionIds: Array<bigint>;
}
export interface UserStats {
    totalPracticeAttempts: bigint;
    userId: Principal;
    totalPracticeCorrect: bigint;
    topicStats: Array<[bigint, bigint, bigint]>;
    lastActiveDate: string;
    studyStreak: bigint;
}
export interface backendInterface {
    getMockExam(id: bigint): Promise<MockExam | null>;
    getMockExamQuestions(examId: bigint): Promise<Array<Question>>;
    getMockExams(): Promise<Array<MockExam>>;
    getMyExamHistory(): Promise<Array<ExamAttempt>>;
    getMyStats(): Promise<UserStats>;
    getMyTopicStats(): Promise<Array<[bigint, bigint, bigint]>>;
    getQuestions(topicId: bigint): Promise<Array<Question>>;
    getTopic(id: bigint): Promise<Topic | null>;
    getTopics(): Promise<Array<Topic>>;
    submitExamAttempt(examId: bigint, answers: Array<ExamAnswer>): Promise<ExamAttempt>;
    submitPracticeAnswer(topicId: bigint, questionId: bigint, selectedIndex: bigint): Promise<PracticeResult>;
}
import type { MockExam as _MockExam, Topic as _Topic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getMockExam(arg0: bigint): Promise<MockExam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockExam(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockExam(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockExamQuestions(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockExamQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockExamQuestions(arg0);
            return result;
        }
    }
    async getMockExams(): Promise<Array<MockExam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockExams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockExams();
            return result;
        }
    }
    async getMyExamHistory(): Promise<Array<ExamAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyExamHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyExamHistory();
            return result;
        }
    }
    async getMyStats(): Promise<UserStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return result;
        }
    }
    async getMyTopicStats(): Promise<Array<[bigint, bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTopicStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTopicStats();
            return result;
        }
    }
    async getQuestions(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions(arg0);
            return result;
        }
    }
    async getTopic(arg0: bigint): Promise<Topic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopic(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopic(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopics(): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopics();
            return result;
        }
    }
    async submitExamAttempt(arg0: bigint, arg1: Array<ExamAnswer>): Promise<ExamAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExamAttempt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExamAttempt(arg0, arg1);
            return result;
        }
    }
    async submitPracticeAnswer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<PracticeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPracticeAnswer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPracticeAnswer(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MockExam]): MockExam | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Topic]): Topic | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
